export const actions = {
    FETCH_TODO_LIST: "FETCH_TODO_LIST",
    ADD_NEW_TODO: "ADD_NEW_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
    UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE",
    FETCH_TODO_LIST_SUCCESS: "FETCH_TODO_LIST_SUCCESS",
    FETCH_TODO_LIST_FAILURE: "FETCH_TODO_LIST_FAILURE",
    ADD_NEW_TODO_SUCCESS: "ADD_NEW_TODO_SUCCESS",
    ADD_NEW_TODO_FAILURE: "ADD_NEW_TODO_FAILURE",   
    DELETE_TODO: "DELETE_TODO",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE", 
}